cusswords:
  - fuck
  - shit
  - ass
  - damn
  - dick
  - nigger
  - asshole
  - cunt
  - pussy
  - bitch
  - bitches
  - douche
  - douchebag
  - douches
warnmessage: Don't cuss!
kickmessage: You were kicked for cussing!
cost: 100
chatOnMessage: Chat has been enabled!
chatOffMessage: Chat has been disabled!
cancelChatMessage: You can't talk while the chat is disabled!
killOnCurse: false
killMessage: You were killed for cussing!
capsPercentage: 75